### ISSUE TITLE
Does the Desktop App works on MacOS aswell?

### ISSUE THREAD

**Issue by blakstrox** [narender-rk10/MyRemoteDesk-Complete-Workspace-Integrated-Platform#2]
May I know the Desktop app works on both windows and Mac Os? Also how we can configure the server details in the desktop app?

**Comment by narender-rk10** [comment]
Hi, It should work because it is an electron app which have the cross platform development support.

We have not tested on Mac OS

But there are some ways you can integrate with Mac OS

You can configure the server details on desktop app
